### ISSUE TITLE
Cannot build NServiceBus.Autofac 5.0

### ISSUE THREAD

**Issue by kevin-whalley-gc** [Particular/NServiceBus.Autofac#13] opened 2016-05-11 00:15 UTC
Hi,

I checked out the repo and switched to the commit that was tagged and encountered several issues.

I checked it out into a folder independent of my solution, and then added it as a project reference, it has several 'EnsureNuGetPackageBuildImports' targets in the project file which are relative, meaning I had to copy it into my solution folder for them to resolve

I could not find the Mono.Cecil binary it was looking for, even though I grabbed the past two publicly available NuGet packages.

I am attempting to compile and execute the code so I could identify why I am having an exception thrown for a missing registration that I reasonably believe I have made

**Comment by boblangley** [comment] 2016-05-11 00:33
Hey Kevin. It is an issue with Visual Studio 2015 and the version of Fody referenced. We will need to prioritize updating the branch and moving the tag.

**Comment by SimonCropp** [comment] 2016-05-11 00:35
@kevin-whalley-gc what r u trying to achieve?

**Comment by kevin-whalley-gc** [comment] 2016-05-11 00:44
@SimonCropp 

I am attempting to compile and execute the code so I could identify why I am having an exception thrown for a missing registration that I reasonably believe I have made

**Comment by SimonCropp** [comment] 2016-05-11 01:03
ok in that case try this

 * get master
 * do a nuget update (to get the newer version of fody)
 * build
 * take the binaries and copy them into the package dir in your solution dir

You will now be able to set break on all exceptions and VS will find the correct files

i am simon.cropp on skype if u need more help

**Comment by kevin-whalley-gc** [comment] 2016-05-11 17:06
Thanks @SimonCropp I'll give this a go

**Comment by kevin-whalley-gc** [comment] 2016-05-11 18:53
Thanks @SimonCropp, I was able to troubleshoot.

**Comment by kevin-whalley-gc** [comment] 2016-05-11 18:56
@boblangley FYI I am using VS2013

**Comment by SimonCropp** [comment] 2016-05-11 21:23
@kevin-whalley-gc unfortunatly we r in the process of updating all our repos to target 2015 only. Ie still compat with earlier .net but to build the codebases locally you will need a copy of 2015 in the near future. I apologise for any inconvenience this may cause. 

Re your troubleshooting what was the cause of the issue? Anything we can fix on our side?

**Comment by danielmarbach** [comment] 2016-09-01 10:46
Closing this one. We support VS215 only.

**Closed by danielmarbach** 2016-09-01 10:46 UTC
Labels: Size: S, Tag: Maintainer Prio
